[package]
name = "vodozemac-cpp"
version = "0.1.0"
edition = "2021"

[lib]
name = "vodozemac"
crate-type = ["staticlib"]

[dependencies]
anyhow = "1.0.42"
cxx = "1.0"
vodozemac = "0.2"

[build-dependencies]
cxx-build = "1.0"
